### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by eitanaviv** [tntkhang/realm-encryption-helper#1]
Hi there,
Thanks for this library, but unfortunately i can't get it to work.
Crashes on my Galaxy S8+ and on Android Studio Emulator.
I used your example..

**Comment by tntkhang** [comment]
Thanks for reporting a bug,
Which android version you used on Galaxy S8+ and emulator ? Could you please post the crash log over here for me to easy to fix it.
Thanks.

**Comment by tntkhang** [comment]
Thank for reporting this bug, I checked and found the solution, could you update to version 1.0.1 for fixing this bug

```
implementation 'com.github.tntkhang:realm-encryption-helper:1.0.1'
```
I will update the current version to fix this issue and short the dependencies
Thanks.
