### ISSUE TITLE
Logmessages with key 

### ISSUE THREAD

**Issue by genie137** [tntkhang/realm-encryption-helper#3]
Hey,

I like your libary, but can you make it so that the encrypted key is not being logged?
Its not so secure ;-);
Maby by having a log boolean in the initHelper to disable logging?

**Comment by tntkhang** [comment]
Thank Genie,  I will remove and update library version, those logs for development purpose and I forgot remove it when build a library :)

**Comment by tntkhang** [comment]
Disable debug log is updated in version 1.0.2
